server.port=8080
app.greeting=Ciao
management.endpoints.web.exposure.include=health,info
management.info.env.enabled=true

info.app.name=My First Spring Boot Application
info.app.description=This is done with simple REST API
info.app.version=1.0.0
