<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>com.lhind</groupId>
  <artifactId>hotel-reservation-system</artifactId>
  <version>1</version>
  <packaging>pom</packaging>
  <name>Hotel Reservation Management System</name>

  <parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>4.1.0</version>
  </parent>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <java.version>21</java.version>
    <log4jdbc.log4j2.version>1.16</log4jdbc.log4j2.version>
    <rest.assured.version>2.3.3</rest.assured.version>
  </properties>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>com.lhind</groupId>
        <artifactId>hotel-core</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.bgee.log4jdbc-log4j2</groupId>
        <artifactId>log4jdbc-log4j2-jdbc4.1</artifactId>
        <version>${log4jdbc.log4j2.version}</version>
      </dependency>
      <dependency>
        <groupId>com.jayway.restassured</groupId>
        <artifactId>rest-assured</artifactId>
        <version>${rest.assured.version}</version>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <modules>
    <module>hotel-core</module>
    <module>hotel-api</module>
  </modules>

  <build>
    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-compiler-plugin</artifactId>
          <configuration>
            <annotationProcessorPaths>
              <path>
                <groupId>org.projectlombok</groupId>
                <artifactId>lombok</artifactId>
              </path>
            </annotationProcessorPaths>
          </configuration>
        </plugin>
      </plugins>
    </pluginManagement>
  </build>

</project>
